location = 200;
fault = 1010;
current = c(:,2:4);
current(:,4) = fault;
current(:,5) = location;
voltage = v(:,2:4);
logg = [voltage,current];
data = xlsread('sdata1');
data = [data;logg];
xlswrite('sdata1',data);